# https://prettier.io/docs/en/options.html
# 行长度(大概)
printWidth: 100
# 缩进的空格数
tabWidth: 4
# 使用tab缩进/(空格缩进)
useTabs: false
# 语句末尾添加分号/false仅在可能导致ASI故障的行的开头添加分号。
semi: false
# 使用单引号 / 双引号
singleQuote: true
# as-needed / consistent / preserve
quoteProps: as-needed
# jsx中使用单引号 /双引号
jsxSingleQuote: true
# 尾随逗号
trailingComma: es5
# 对象字面量与括号之间的空格 true:{ foo },false:{foo}
bracketSpacing: true
# 同一行的jsx反括号 / 独立一行
jsxBracketSameLine: false
# 箭头函数 1个参数也加括号 (always / avoid)
arrowParens: avoid

# rangeStart: 0
# rangeEnd: Infinity

# 换行符 (lf / crlf / cr / auto )
endOfLine: lf
